# .github/workflows/dotnet.yml
name: .NET

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8 & 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build (all target frameworks)
      run: dotnet build --no-restore --configuration Release

    - name: Run tests (all target frameworks)
      run: dotnet test --no-build --configuration Release --verbosity normal

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8 & 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x

    - name: Extract version from tag
      id: extract_version
      shell: bash
      run: |
        echo "Extracting version from tag..."
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Resolved version: $VERSION"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build (all target frameworks)
      run: dotnet build --no-restore --configuration Release

    - name: Pack (multi-target)
      run: dotnet pack --no-build --configuration Release -o ./nupkg /p:PackageVersion=${{ env.VERSION }}

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
